
####### Application Url and html report formatter ##############
default: features -x -r support -r features/step_definitions --format html --out log/cucumber.html --format pretty PAGE_URL=https://www.goodsearch.com/
