# Gem files which we are going to use in our frame work
# Each Gem has its own dependents



source "https://rubygems.org"

group :development, :test do
gem 'rspec-rails'
gem 'capybara'
gem 'selenium-webdriver'
gem 'chromedriver-helper'
gem 'cucumber'
gem 'page-object'
gem 'require_all'
gem 'site_prism'



end

